### ISSUE TITLE
use the handlers in the light-4j ingress-router module and build a sample test config

### ISSUE THREAD

**Issue by chenyan71** [networknt/light-router#101]
The router handle has been moved to light-4j egress-router module.

the light-router will use the handlers by adding dependency.

**Comment by stevehu** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [use the handlers in the light-4j ingress-router module and build a sample test config light-router master](https://trello.com/c/icFQR2Mi/1099-use-the-handlers-in-the-light-4j-ingress-router-module-and-build-a-sample-test-config-light-router-master)
