### ISSUE TITLE
change the local sample to extend config for handler.yml

### ISSUE THREAD

**Issue by chenyan71** [networknt/light-router#103]
In the real deployment, usually the router path handler may need change based on requirement. So the handler.yml need extended out to values.yml. Changed the demo sample to use values.yml to extend handler.yml config values

**Comment by stevehu** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [change the local sample to extend config for handler.yml light-router master](https://trello.com/c/2MVFm0Mi/1103-change-the-local-sample-to-extend-config-for-handleryml-light-router-master)
