### ISSUE TITLE
Add new handler to support SAML grant type flow

### ISSUE THREAD

**Issue by miklish** [networknt/light-router#17]
Support must be added to support the new SAML grant type OAuth flow.

A new handler, SAMLGrantHandler, will be added to support this OAuth flow.

Light Router must accept a JWT and a SAML token in it's header under the header keys `assertion` (for SAML) and `client_assertion` (for JWT).

It must then `POST` these tokens* to an OAuth authorization server (encoded as `x-www-for-urlencoded`) and receive a JWT in response, and then set this new `Bearer {JWT}` in its header under the `Authorization` key before service lookup and forwarding the request. 

* - In addition to the two tokens, the authorization server expects the following additional values in x-www-form-urlencoded payload:

- `grant_type: urn:ietf:params:oauth:grant-type:saml2-bearer`
- `scope: {blank separated list of OAuth scopes}`*
- `client_assertion_type: urn:ietf:params:oauth:client-assertion-type:jwt-bearer`

`*` Note that the scope key/value pair is optional.

**Comment by stevehu** [comment]
This is implemented by the PR from @dguncb
