### ISSUE TITLE
upgrade light-router to use handler.yml instead of PathProvider

### ISSUE THREAD

**Issue by stevehu** [networknt/light-router#26]
We need to serve the static content from the router instance and it would be easier to use handler.yml instead of PathProvider. The other benefit of hanlder.yml is the validate the path and method before routing the request to the downstream service. What do you think?

**Comment by stevehu** [comment]
As both HandlerProvider and handler.yml are supported, the real question is should we drop the HandlerProvider?

**Comment by ddobrin** [comment]
I have migrated all APIs at my client to use the new handler, as they require independent paths per endpoint, however dropping it at this time would be a backwards incompatible change.

I support the usage of the handler.yml, however I am not sure whether development teams have migrated to make good use of it

**Comment by stevehu** [comment]
We can keep both options open in this case. Which one should be the default then? Or just let the users choose based on the configuration?

**Comment by stevehu** [comment]
In either case, we need to add a RouterHandler that is ready to be added to the handler.yml config file. I am checking in one implementation.

**Comment by stevehu** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Add RouterHandler for handler.yml](https://trello.com/c/iGSTRe82/16-add-routerhandler-for-handleryml)
