### ISSUE TITLE
Junit test class created for SAMLTokenHandler

### ISSUE THREAD

**Issue by sreenicibc** [networknt/light-router#27]
Junit test class created for SAMLTokenHandler(Jira API-22).

**Comment by NicholasAzar** [comment]
Associated pr: https://github.com/networknt/light-router/pull/28

**Comment by NicholasAzar** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Update router test case for SAML token handler](https://trello.com/c/Z8tSpVNC/26-update-router-test-case-for-saml-token-handler)
