### ISSUE TITLE
Router Auth Exception Handling

### ISSUE THREAD

**Issue by BalloonWen** [networknt/light-router#41]
Provide router ability to handle error scenarios(currently only for authorization errors).
The router should get JWT when auth server has a success response.
The router should send a response to the client when the auth server response an error.
Related RFC doc https://github.com/networknt/light-rfcs/blob/master/light-router/0002-exception-handling-token-get-refactor.md

**Comment by stevehu** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Router Auth Exception Handling](https://trello.com/c/FGIjxJaF/90-router-auth-exception-handling)
