### ISSUE TITLE
Host header setting incorrect for outbound HTTP calls

### ISSUE THREAD

**Issue by neil-leighton** [networknt/light-router#5]
The Host header for the outbound HTTP connection is being set with the inbound host name. This prevents usage of downstream applications that use the Host header for routing such as Azure web apps.
Need to set the Host header using the outgoing host name and port from RouterProxyClient on the first connection (ConnectNotifier) and for subsequent calls using a cached open connection.

**Comment by stevehu** [comment]
Just set the following configuration in router.yml will ensure that target host is set in the host header.
```
# Rewrite Host Header with the target host and port and write X_FORWARDED_HOST with original host
rewriteHostHeader: true
```
